#[derive(PartialEq, Clone, Debug)]
pub enum EntryKind {
    AddTag,
    Categorize,
    DeleteConfirmation,
    Find,
    FindCategory,
    FindLabel,
    FindName,
    FindSubCategory,
    GridSize,
    Help,
    Information,
    Label,
    MoveConfirmation,
    MoveToLabelConfirmation(String),
    Number,
    Order,
    Rank,
    RemoveTag,
    Rename,
    SetRestriction,
    SetSelection,
}
