#!/usr/bin/env sh
git todo
nb_srce="$(git status -s|grep \.rs|wc -l)"
if [ $nb_srce -gt 1 ] ; then
    git status -s
    echo "commit reverse all these files ?"
    read response
    if [ "$response" != "y" ] ; then
        exit 1
    fi
fi
cargo test --no-run
