width = 800
height = 800
database_file = "/Users/tof/Coding/gsr2/testdata/gsr2.db"
temp_dir = "/Users/tof/Coding/gsr2/testdata/subdir"
current_picture = "/Users/tof/Coding/gsr2/testdata/nine_colors.png"
current_pictures_per_row = 2
current_order = "Name"
cover = false
base_dir = "/Users/tof/Coding/gsr2/testdata"
catalog_filepath = "/Users/tof/Coding/gsr2/testdata/catalog.sexp"

[marked]
